export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_QUESTIONS_CARD = "SET_QUESTION_CARD";
export const SET_SCORE = "SET_SCORE";
export const SET_PROGRESS = "SET_PROGRESS";
export const GET_QUESTIONS = "GET_QUESTIONS";
